### ISSUE TITLE
cmake: make install works but do nothing

### ISSUE THREAD

**Issue by mramotowski** [ldorau/strace.ebpf#10]
> make install
> [  4%] Built target check_license_executable
> [  9%] Built target test_syscalls
> [ 25%] Built target strace
> [ 79%] Built target ebpf
> [ 95%] Built target strace.ebpf
> [100%] Built target file_sc_bench
> Install the project...
> -- Install configuration: ""
> make uninstall
> make: *** No rule to make target 'uninstall'.  Stop.

**Comment by ldorau** [comment]
@mramotowski please split this issue into two: this one rename to "cmake: make install works but do nothing", verify and close and submit a new one for uninstall
