### ISSUE TITLE
make: warning: too many arguments for format [-Wformat-extra-args]

### ISSUE THREAD

**Issue by mramotowski** [ldorau/strace.ebpf#15]
Found on 3b3b8d92bbcfec51949bfa30ddf9194fc2307745

> /home/mramotow/repos/pmemfile/strace.ebpf/src/utils.c: In function ‘check_bpf_jit_status’:
> /home/mramotow/repos/pmemfile/strace.ebpf/src/utils.c:241:17: warning: too many arguments for format [-Wformat-extra-args]
>    fprintf(file, "ERROR: cannot read status of "
>                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by ldorau** [comment]
Please verify and close.

**Comment by mramotowski** [comment]
Verified on 63dedf118b0f72009d9f78fa14da1ec8d8a6cdb2
