### ISSUE TITLE
build: repository does not build

### ISSUE THREAD

**Issue by mramotowski** [ldorau/strace.ebpf#17]
Found on revision: d80a218ad946278138d88da589e925af7c883e17 with gcc 5.4 on kernel 4.8.0-34 and 4.9.4-rc4. On kernel 4.9.4 it is building.

> /home/mramotow/repos/pmemfile/strace.ebpf/src/bpf_ctx.c: In function ‘attach_callback_to_perf_output’:
> /home/mramotow/repos/pmemfile/strace.ebpf/src/bpf_ctx.c:141:41: warning: passing argument 3 of ‘bpf_open_perf_buffer’ makes pointer from integer without a cast [-Wint-conversion]
>     bpf_open_perf_buffer(callback, NULL, -1, cpu,
>                                          ^
> In file included from /home/mramotow/repos/pmemfile/strace.ebpf/src/bpf_ctx.c:46:0:
> /usr/include/bcc/libbpf.h:72:8: note: expected ‘void *’ but argument is of type ‘int’
>  void * bpf_open_perf_buffer(perf_reader_raw_cb raw_cb,
>         ^
> /home/mramotow/repos/pmemfile/strace.ebpf/src/bpf_ctx.c:141:4: error: too few arguments to function ‘bpf_open_perf_buffer’
>     bpf_open_perf_buffer(callback, NULL, -1, cpu,
>     ^
> In file included from /home/mramotow/repos/pmemfile/strace.ebpf/src/bpf_ctx.c:46:0:
> /usr/include/bcc/libbpf.h:72:8: note: declared here
>  void * bpf_open_perf_buffer(perf_reader_raw_cb raw_cb,
>         ^
> src/CMakeFiles/strace.ebpf.dir/build.make:146: recipe for target 'src/CMakeFiles/strace.ebpf.dir/bpf_ctx.c.o' failed
> make[2]: *** [src/CMakeFiles/strace.ebpf.dir/bpf_ctx.c.o] Error 1
> CMakeFiles/Makefile2:314: recipe for target 'src/CMakeFiles/strace.ebpf.dir/all' failed
> make[1]: *** [src/CMakeFiles/strace.ebpf.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by ldorau** [comment]
What version of libbcc do you use in all cases? strace.ebpf requires libbcc v.0.3.0

**Comment by mramotowski** [comment]
> -- Checking for module 'libbcc'
> --   Found libbcc, version 0.3.0
> -- Configuring done

**Comment by ldorau** [comment]
@mramotowski Fix applied, please verify and close

**Comment by ldorau** [comment]
API of libbcc has changed at: https://github.com/iovisor/bcc/commit/4b764de6bcb3655b29b2fb6df6c9c65b7a31338c
strace.ebpf requires libbcc v0.3.0-65-g4b764de or later since now on.

**Comment by mramotowski** [comment]
Verified on b8b9c5caa51b17c5e8ae8d0b6b0fcbb94203c41e
