### ISSUE TITLE
compilation: strace.ebpf do not compile under gcc-4.8.5 

### ISSUE THREAD

**Issue by mramotowski** [ldorau/strace.ebpf#4]
strace.ebpf do not compile under gcc-4.8.5 

> /home/mramotow/repos/pmemfile/strace.ebpf/src/libstrace/strace_bpf.c: In function ‘attach_callback_to_perf_output’:
> /home/mramotow/repos/pmemfile/strace.ebpf/src/libstrace/strace_bpf.c:139:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
>   for (int cpu = 0; cpu < cpu_qty; cpu++) {
>   ^
> /home/mramotow/repos/pmemfile/strace.ebpf/src/libstrace/strace_bpf.c:139:2: note: use option -std=c99 or -std=gnu99 to compile your code
> /home/mramotow/repos/pmemfile/strace.ebpf/src/libstrace/strace_bpf.c: In function ‘detach_all’:
> /home/mramotow/repos/pmemfile/strace.ebpf/src/libstrace/strace_bpf.c:191:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
>   for (unsigned i = 0; i < b->pr_arr_qty; i++) {
>   ^
> src/libstrace/CMakeFiles/strace.dir/build.make:62: recipe for target 'src/libstrace/CMakeFiles/strace.dir/strace_bpf.c.o' failed
> make[2]: *** [src/libstrace/CMakeFiles/strace.dir/strace_bpf.c.o] Error 1
> CMakeFiles/Makefile2:547: recipe for target 'src/libstrace/CMakeFiles/strace.dir/all' failed
> make[1]: *** [src/libstrace/CMakeFiles/strace.dir/all] Error 2
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by ldorau** [comment]
Thanks for the fix. It is merged. Please verify and close.

**Comment by mramotowski** [comment]
Verified on 9489b1cf8030f52f460a3363b31b40b87b1076c7
