### ISSUE TITLE
compilation: strace.epbf gives warning when compiled with gcc 6.2.0

### ISSUE THREAD

**Issue by mramotowski** [ldorau/strace.ebpf#5]
Strace.epbf gives warning when compiled with gcc 6.2.0

> /home/mramotow/repos/pmemfile/strace.ebpf/test/test_syscalls.c: In function ‘test_unsupported_syscalls’:
> /home/mramotow/repos/pmemfile/strace.ebpf/test/test_syscalls.c:126:2: warning: ignoring return value of ‘chroot’, declared with attribute warn_unused_result [-Wunused-result]
>   chroot(NON_EXIST_PATH_1);
>   ^~~~~~~~~~~~~~~~~~~~~~~~
> /home/mramotow/repos/pmemfile/strace.ebpf/test/test_syscalls.c: In function ‘test_basic_syscalls’:
> /home/mramotow/repos/pmemfile/strace.ebpf/test/test_syscalls.c:94:2: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
>   write(fd, buffer, BUF_LEN);
>   ^~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/mramotow/repos/pmemfile/strace.ebpf/test/test_syscalls.c:96:2: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
>   read(fd, buffer, BUF_LEN);
>   ^~~~~~~~~~~~~~~~~~~~~~~~~
> /home/mramotow/repos/pmemfile/strace.ebpf/test/test_syscalls.c:113:2: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
>   write(0x101, buffer, 1);
>   ^~~~~~~~~~~~~~~~~~~~~~~
> /home/mramotow/repos/pmemfile/strace.ebpf/test/test_syscalls.c:114:2: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
>   read (0x102, buffer, 2);
>   ^~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> /home/mramotow/repos/pmemfile/strace.ebpf/test/test_syscalls.c: In function ‘test_unsupported_syscalls’:
> /home/mramotow/repos/pmemfile/strace.ebpf/test/test_syscalls.c:126:2: warning: ignoring return value of ‘chroot’, declared with attribute warn_unused_result [-Wunused-result]
>   chroot(NON_EXIST_PATH_1);
>   ^~~~~~~~~~~~~~~~~~~~~~~~
> /home/mramotow/repos/pmemfile/strace.ebpf/test/test_syscalls.c: In function ‘test_basic_syscalls’:
> /home/mramotow/repos/pmemfile/strace.ebpf/test/test_syscalls.c:94:2: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
>   write(fd, buffer, BUF_LEN);
>   ^~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/mramotow/repos/pmemfile/strace.ebpf/test/test_syscalls.c:96:2: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
>   read(fd, buffer, BUF_LEN);
>   ^~~~~~~~~~~~~~~~~~~~~~~~~
> /home/mramotow/repos/pmemfile/strace.ebpf/test/test_syscalls.c:113:2: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
>   write(0x101, buffer, 1);
>   ^~~~~~~~~~~~~~~~~~~~~~~
> /home/mramotow/repos/pmemfile/strace.ebpf/test/test_syscalls.c:114:2: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
>   read (0x102, buffer, 2);
>   ^~~~~~~~~~~~~~~~~~~~~~~
>

**Comment by ldorau** [comment]
@mramotowski  Thanks for the fix. It is merged. Please verify and close.

**Comment by mramotowski** [comment]
Verified
