### ISSUE TITLE
strace.ebpf should wait for all children of the traced process until they exit

### ISSUE THREAD

**Issue by ldorau** [ldorau/strace.ebpf#9]

**Comment by ldorau** [comment]
Fixed by https://github.com/ldorau/strace.ebpf/commit/cc41b88c3291f72f828d07a4384583470494be41

**Comment by ldorau** [comment]
Fixed by https://github.com/ldorau/strace.ebpf/commit/02df49d08a48771ca7251e0fddf37517f006657b

**Comment by vitalyvch** [comment]
It is good to enable this by cl option. Children sometimes are not interested.

**Comment by ldorau** [comment]
Done: https://github.com/ldorau/strace.ebpf/commit/0d6cc14840b8e152a1cde15950d0e45830c8caf3
Thanks.

**Comment by ldorau** [comment]
Actually in https://github.com/ldorau/strace.ebpf/commit/8b8df9c81728de8c9a11a44e6659201a6194eaba
